# Generated by Django 5.0.3 on 2024-03-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo_postal', models.CharField(max_length=45)),
                ('cuenta_bancaria', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True)),
                ('rfc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('materno', models.CharField(max_length=45)),
                ('paterno', models.CharField(max_length=45)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('ine', models.CharField(blank=True, max_length=45, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('notificaciones', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('colonia', models.CharField(blank=True, max_length=45, null=True)),
                ('calle', models.CharField(blank=True, max_length=45, null=True)),
                ('num_ext', models.CharField(blank=True, max_length=5, null=True)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('servicio_ofrecido', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Artesano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_materno', models.CharField(max_length=45)),
                ('apellido_paterno', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rfc', models.CharField(max_length=45)),
                ('ine', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_tarjeta', models.CharField(max_length=45)),
                ('enfoque', models.TextField(blank=True, max_length=256, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.cooperativa')),
            ],
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='paqueteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.paqueteria'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
                ('categoria', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True)),
                ('material', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('artesano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.artesano')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, max_length=255, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_user', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=45)),
                ('datos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.datos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.rol')),
            ],
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.usuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('gasto_envio', models.FloatField(blank=True, null=True)),
                ('total_sn', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('numero_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=45, null=True)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.venta')),
            ],
        ),
    ]
