# Generated by Django 5.0.3 on 2024-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
