# Generated by Django 5.0.3 on 2024-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0006_alter_usuario_contrasenia_alter_usuario_rol_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('no_publicado', 'No Publicado')], default='no_publicado', max_length=12),
        ),
    ]
