# Generated by Django 5.0.3 on 2024-04-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0007_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_productos/'),
        ),
    ]
