# Generated by Django 5.0.3 on 2024-05-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0017_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='datos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tunanibackapp.datos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tunanibackapp.rol'),
        ),
    ]
