# Generated by Django 5.0.3 on 2024-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0019_remove_usuario_contrasenia_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(default='contrasenia', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
