# Generated by Django 5.0.3 on 2024-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0020_usuario_contrasenia_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pedido',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12),
        ),
    ]
