# Generated by Django 5.0.3 on 2024-05-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunanibackapp', '0022_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativa',
            name='paqueteria',
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='paqueteria_asignada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperativa_asignada', to='tunanibackapp.paqueteria'),
        ),
        migrations.AddField(
            model_name='paqueteria',
            name='cooperativa',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='paqueterias', to='tunanibackapp.cooperativa'),
            preserve_default=False,
        ),
    ]
